apiVersion: v2
name: keptn-flux-integration
description: A Helm chart for the Keptn Flux Integration

type: application

version: 0.13.0
appVersion: "0.16.0"

home: "https://keptn.sh"
icon: "https://raw.githubusercontent.com/cncf/artwork/master/projects/keptn/icon/color/keptn-icon-color.svg"
sources:
  - "https://github.com/keptn-sandbox/keptn-flux-integration"
annotations:
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/links: |
    - name: support
      url: https://github.com/keptn-sandbox/keptn-flux-integration/issues
keywords:
  - cloud-native
  - orchestration
  - cd
  - keptn
